USE BookDB;

ALTER TABLE BookInventory WITH CHECK
ADD CONSTRAINT FK_GenreID FOREIGN KEY(GenreID) REFERENCES Genre(GenreID)
ON UPDATE CASCADE
GO

ALTER TABLE BookInventory
ADD CONSTRAINT FK_PublisherID FOREIGN KEY(PublisherID) REFERENCES Publisher(PublisherID)
GO

ALTER TABLE BookInventory WITH CHECK
ADD CONSTRAINT FK_BookFormatID FOREIGN KEY(BookFormat) REFERENCES BookFormat(BookFormatID)
ON UPDATE CASCADE
GO

ALTER TABLE BookInventory
ADD CONSTRAINT FK_AuthorID FOREIGN KEY(AuthorID) REFERENCES Author(AuthorID)
GO

ALTER TABLE Loaned
ADD CONSTRAINT FK_BorrowerID FOREIGN KEY(BorrowerID) REFERENCES Borrower(BorrowerID)
GO

ALTER TABLE Loaned
ADD CONSTRAINT FK_BookID FOREIGN KEY(BookID) REFERENCES BookInventory(BookID)
ON UPDATE CASCADE
ON DELETE CASCADE



